language: java
env:
  matrix:
  - JDK=8
dist: trusty
matrix:
  allow_failures:
  - env: JDK=8-ea
deploy:
  provider: heroku
  api_key:
    secure: oH2LbB3DnGx0vtK8UyIrxwCvIraJVowf4x5TugNJYq2F8ZrXltr/ZF46VYRYRwvUvB8SI+x+CjpU0ncAMEnZ8FUJsyKiOGAHHuTDxev4X6B/dYnsj7z/dCrYoB0etPcGA5d3fwQ4CxnEodjQZ2h6iC5WTqhj5R17ik+fGSG+Nh5/NgzmlPaRcfXSmp5sv3U9xE4rYzmcGMJgn5HE0bNkx8YC2NIeO5zwIL1k6y4AoNS1mTrpyp/YoofywVx4ydFWEMdXuzjy+EFrHagGz2DgwC0dy6Z79cn4Qn/k6JPmk6ko3NbjUq7unABXrc5t//OIEk5bupzmtsKn/79Po7HZ3Po/hJ0h9ugfOZKX5POol4cDNKFvhbQV/WO4PyWMi8Vp15iCRvwRcJJAVL+jdqRvdH5d8WhHLrYuf0NURjaELsE+B9+CII/vbbgnhzPOckqy5YStxfC/WVEVqhvhM9MLCBkedJmhDbfAqMWd+VHYD3lQvq7FedHf2lIIpe1l0U6c4DVEP1FZjrWMhZtBzkgTympG+aBGrjeoh9sRMnTNFH1Ei7kX2GdicNoDCP+f20/FU3RR7+4PGkJbuEaQICC9TuRWxueEHQLnP/MeJ6WqpfDnMUMeChsRoV8+zq145YGFujN072UU+D01sDjthhviTEXYb+lKfwrUKQvKcEc6D0Q=
  app: limitless-dawn-63121
  on:
    repo: mrkansa/baby
