language: java
env:
  matrix:
  - JDK=8
dist: trusty
matrix:
  allow_failures:
  - env: JDK=8-ea
deploy:
  provider: heroku
  api_key:
    secure: GN6utopVFvqyhQKdVk/CLjgNj2u3xn4BMBuD29EdbKZApn5xfjCylWELTAOKsqZPkU0k0AJDNS+cv6DieR9GP60UgXVT77oAC0JsP+dMbr7W8yEqj1KDsTPlVFFsRY0IoMIaMfTwCitAPMiM/+JI8lfxKqktXz7HeA5ZUwO9hwNxEtg/qGJMnrDBFYxnWcj6l3fh0DwcEliDIdmW1zmkgbnuLcFaN7mvGyLas81Zf+aTGzwkSail/FSkSR/9r0eWGBzM1ypK30OhhyAxTxs1uYQJaRV3Fnz5OwoWGA1OB5coJ7cMDZb5/e+0UMpXWjRJS8fnYxauCnHk56QuuKHqZXbxLEobWAJsv0dBI3jf5dOQVi3hyGrMbPIv3Un34QY3TcSQyMZeRJ9Q1weZ/jy+BzxnEMo73kvVsSrOdsWHRDE/hOPkLjT6+8t60Jo4M342xs8JzAdJdK2z539U4rnE/k/HFEvLAFfrK7l9ppF//lBhN/wE2aqzQ6WM8tT7yBJ4pqWTPaOZWzGqe5MW29Wbe+D2xwEHwA+1hKfcsXo06gBPIpSgC6vkKbCD6SSRdDYWx7hk5H8wksazrxZcfHsON1Zyoe3bk+aXkBFg/1O9R61WQJ/ndnis/MOEtLMdiK71HakROg/kbtnK7s+5kop5MGw65pPb2m4AiMbkG4HD6WM=
  app: limitless-dawn-63121
  on:
    repo: mrkansa/baby
