language: java
env:
  matrix:
  - JDK=8
dist: trusty
matrix:
  allow_failures:
  - env: JDK=8-ea
deploy:
  provider: heroku
  api_key:
    secure: SiLV+WimM5Mgf1s649b2pluP7dYj3jNhGcjXyiC6ZMeNkEVHUN9tysEZX6ALL9U/5BG69i5S6k9AMkw1eE4LAZcWGPzm8ysuzDxuA+RGOri3WSjgx4kvBCf9lKlAEq8pdUOM2YRm0+lgXW1roT3yMhaum+1QdlvYY5rCcRH4OD+Bqnoj3z/fLO3nuHYkoQxGJsFOn1sYLo7Qn9WtAK5cpjsfxGwIbNgI+BFeiZ5+Kd5Zp6nR2QoNLYskvh6Eh4kwrPjTXIqNrrQC0wqjja88tiHaqse9qMI5C2ORMMrDZun8AeLRCxNaO0yTrgbhVABpq+PDMtxPCjTD3O9sHReWsPF/KVkG3rBWqWvC9/sfLCAh+xKfexaequIQdjWE33668wLJdZVg4RVQaWnINPKfuG/qwconNxhih6faEtbS66yJHgxZMZ80dq2UDLEPEff3m7mNzN7Jd0kv7gvn6GxPsSGb9l6VbsehBhr7TjXvY3mb8zCb7gay5q1N8j67aHQ0y7jKB5Lo5vIH9Uj6T3Y+sh27PNAla+NPVOqxJejxG3pl2t5ZbOV1pSn7JWj6mRZsynGMLpQ+c9a96LjwnLUyBA+ZZecSD4kdLadxnpGsm86+TuGZ5wsZUaBJirmn750waCE7sfzQyVF9FnojE4pStFiX3MP/PQ1x+QelOGGS4+k=
  app: limitless-dawn-63121
  on:
    repo: mrkansa/baby
