language: java
env:
  matrix:
  - JDK=8
  global:
    secure: dQ9X+7OXZu6VdhXgJuGr3z32L2xBIO5NeNvq8JXxJEjmC6JUxXq1byJT4GrQEKIbSYIIj6pCy+/pr8tkL2VwXXqRvcGaPSswbjb88BFIAnvgHTenKNpFdQ7MkJuQQbqc7qE4H4vrwiIvd6slyafrbw0i3iQsj/tKBqzrGFbmbcXSOnb3LfWa99UIuH4dQAQzQbSB3IY8zf0S7QkaD5gxY/XX+5ooL1XSrpjE3ZoVIRfWxzaO47tcWUsFT+19Qr+hY/Em2aPNzu7xDfUi7sZcLtiHBLTsjfK2kRDOuNWmeHE7mWYaN/WJCumTN6riJnlWNRtxv+Jz/CVmg1TKFVtRMyNYH35ymg5ANS6lGLmuTpa2JYK6TAcTrR18DIa+ry3c8Er0SiBJ1SBO0u3LjAItO3lvQL6dTjrin1Kr3cJlzY4s9KJbAaALBPaO4Eh9/Hacn6wpcAVYq+u4hzex9HtuPpvz7PEbGfBU78PDuE5p2w3Wl9Me2J17b4wc1fRY0kyyHRoDbfPsq4mSJ38oSnHuCHtZtvYfAQHBbiUYnDltqgcOewlh5fuTshmVrTPNuz3nk8EMgp4AZVXqedlBIYspEDH8U76b/Bo4n8ucs6GwZwujg5uGRzeHP4jMlcdhwssdtm/6Fj0ldKDjbG3dTsIUZosMqB42Lflnzj3SKhSK4ew=
dist: trusty
addons:
  apt:
    packages:
    - oracle-java8-installer
matrix:
  allow_failures:
  - env: JDK=8-ea
stages:
- compile
- test
- deploy
deploy:
  provider: pages
  skip_cleanup: true
api_key: "$GITHUB_TOKEN"
  on:
    branch: master
