language:  java

env: 

  - JDK=8

dist: trusty
addons:
  apt: 
    packages:
      - oracle-java8-installer

matrix:
  allow_failures:
    - env: JDK=8-ea

stages:
  - compile
  - test
  - deploy

deploy:
  provider: pages
  skip_cleanup: true
  #local_dir: myfolder/  # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master



#env:
#  - FOO=one
#  - FOO=two

#jobs:
#  include:
#    - stage: compile
#      script: ./compile
#    - stage: deploy
#      script: ./deploy
