language: java
env:
  matrix:
  - JDK=8
dist: trusty
matrix:
  allow_failures:
  - env: JDK=8-ea
deploy:
  provider: hackage
  username: mkansa
  password:
    secure: GOfQz8BUdV9ypr/hUOS9/ViJtPyqN+5w0zsSRznLtP/I1vQYeCzKQc7c+FEcVUJcwIlyreGQCAsqzmyfB3geuaDmvKmRipGsB8aR02NPZgK7JpmzRGb0KD1PGIIF6NIh0XeU81yDdVT3EigTivIUugmyTFo9BWaU1LzZqnP4j3AfNRmJas7bkBd5kHagCZIr7ZOz4cIGsFkpW8pElQEWDsYeBmR7QGlBMRhh+vuGZCiBSICKXVJPVXR5l0TauvcjPTwvo/mCAXMH5Odj6tCXNprZfvB86j8Hxq2iAGVACecRBOAqVycQBtoJUzGq47JnXKO3KOMkfO0xmMfBhYbBgyaxJsDnggj8rbnTwKG9BiPmDNZKzoWVVGxnr5DwpPOJi+xDUATCen8++nzZPnWZaaPJvLOGfQ4B3udpE8Z//tlUZEu4Efg/P6TrLMHcGe4bjNz1iBIDCa+5Gx8tXQP2/IgL5z4iyhYUUT1KeP9cKSM+e6zssmwglhUW0jHsuzZ56qkjLtjbIVB0EewOVwk/hFIQBqPwH47l2nk0RgJ66ZlFtKKWiyWgyjtOYtljxIIep/TC+L0g2iOOStO5GSWec1/3QAVbRm+syo8BWEiXl3fqxKFxnK/Auc+AIHrZmQDpm68rjLgLBNYLP2ffbJ00siT8w+kaENaiFAZzBjEOagY=
  on:
    repo: mrkansa/baby
